### ISSUE TITLE
ABNORMAL_TERMINATION: station_5:station_5_backend

### ISSUE THREAD

**Issue by 24dubstep** [SlvrEagle23/AzuraCast#88] opened 2017-02-01 16:36 UTC
```
23. fXmlRpc\Exception\FaultException
…/­vendor/­lstrojny/­fxmlrpc/­src/­fXmlRpc/­Exception/­FaultException.php:32

>$exception = new static(isset($response['faultString']) ? $response['faultString'] : 'Unknown');

```
```
22. fXmlRpc\Exception\FaultException fault
…/­vendor/­lstrojny/­fxmlrpc/­src/­fXmlRpc/­Parser/­XmlReaderParser.php:373

>throw FaultException::fault($result);
```
```
21. fXmlRpc\Parser\XmlReaderParser parse
…/­vendor/­lstrojny/­fxmlrpc/­src/­fXmlRpc/­Client.php:156

>return $this->parser->parse($response);
```
```
20. fXmlRpc\Client call
…/­vendor/­supervisorphp/­supervisor/­src/­Connector/­XmlRpc.php:45

>return $this->client->call($namespace.'.'.$method, $arguments);
```
```
19. Supervisor\Connector\XmlRpc call
…/­vendor/­supervisorphp/­supervisor/­src/­Supervisor.php:110

>return $this->connector->call('supervisor', $method, $arguments);
```

and more error 

```
18. Supervisor\Supervisor __call
…/­src/­AzuraCast/­Radio/­AdapterAbstract.php113
17. AzuraCast\Radio\AdapterAbstract start
…/­src/­Controller/­Stations/­ProfileController.php91
16. Controller\Stations\ProfileController backendAction
…/­vendor/­slvreagle23/­azuracore/­src/­App/­Mvc/­Controller.php99
15. App\Mvc\Controller dispatch
…/­vendor/­slvreagle23/­azuracore/­src/­App/­Mvc/­Resolver.php42
14. App\Mvc\Resolver App\Mvc\{closure}
<#unknown>0
13. call_user_func
…/­vendor/­slim/­slim/­Slim/­Handlers/­Strategies/­RequestResponse.php41
12. Slim\Handlers\Strategies\RequestResponse __invoke
…/­vendor/­slim/­slim/­Slim/­Route.php340
11. Slim\Route __invoke
…/­vendor/­slim/­slim/­Slim/­MiddlewareAwareTrait.php116
10. Slim\Route callMiddlewareStack
…/­vendor/­slim/­slim/­Slim/­Route.php316
9. Slim\Route run
…/­vendor/­slim/­slim/­Slim/­App.php438
8. Slim\App __invoke
…/­app/­bootstrap.php322
7. Closure {closure}
<#unknown>0
6. call_user_func_array
…/­vendor/­slim/­slim/­Slim/­DeferredCallable.php43
5. Slim\DeferredCallable __invoke
<#unknown>0
4. call_user_func
…/­vendor/­slim/­slim/­Slim/­MiddlewareAwareTrait.php67
3. Slim\App Slim\{closure}
…/­vendor/­slim/­slim/­Slim/­MiddlewareAwareTrait.php116
2. Slim\App callMiddlewareStack
…/­vendor/­slim/­slim/­Slim/­App.php332
1. Slim\App process
…/­vendor/­slim/­slim/­Slim/­App.php293
0. Slim\App run
…/­web/­index.php9
```

**Comment by yehoudatech** [comment] 2017-02-05 20:53
I also have the same problem

**Comment by RainbowDash53** [comment] 2017-03-09 20:05
Bump, i can't restart my station >_>

**Comment by SlvrEagle23** [comment] 2017-04-06 04:31
If this happens again, right after it happens, if you could run `supervisorctl tail station_5:station_5_backend` from an SSH terminal, it may provide some extra information. Feel free to post that here so we can look into it.

**Comment by andbou** [comment] 2017-04-10 12:57
I had the same problem before.
The error disappeared after creating a playlist.
Does at least one active playlistlist exist?

**Comment by SlvrEagle23** [comment] 2017-04-23 22:37
I'm closing this issue as it appears to have been caused by a specific issue that has since resolved itself. Nonetheless, my most recent commits have added significant extra logging to the error page you see when Supervisor fails to start/stop a service, including the process's information, log locations, and the most recent lines in its log (which should definitely indicate the problem).

**Closed by SlvrEagle23** 2017-04-23 22:37 UTC
Labels: bug
