### ISSUE TITLE
update - error

### ISSUE THREAD

**Issue by efsysefsys** [SlvrEagle23/AzuraCast#71] opened 2016-12-09 11:16 UTC
Checking for Ansible: install ok installed
Updating AzuraCast (Environment: production)
HEAD is now at 1946790 Merge branch 'master' of github.com:SlvrEagle23/AzuraCast
Already up-to-date.

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [init : debug] ************************************************************
ok: [localhost] => {
    "msg": "Running Ansible on localhost with OS Ubuntu xenial 16.04 x86_64 (production)"
}

TASK [init : debug] ************************************************************
skipping: [localhost]

TASK [init : Update apt] *******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1

**Comment by mkody** [comment] 2016-12-09 12:30
Like in #58, you're having issues with `apt`, which is unrelated to AzuraCast.
Can you run `apt-get clean` and `apt-get update` and share the output?

**Comment by efsysefsys** [comment] 2016-12-09 13:53
**i do apt-get clean and update and now i get**

TASK [setup] *******************************************************************
ok: [localhost]

TASK [init : debug] ************************************************************
ok: [localhost] => {
    "msg": "Running Ansible on localhost with OS Ubuntu xenial 16.04 x86_64 (production)"
}

TASK [init : debug] ************************************************************
skipping: [localhost]

TASK [init : Update apt] *******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "FATAL -> Failed to fork.\n", "module_stdout": "", "msg": "MODULE FAILURE"}
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1

**Comment by SlvrEagle23** [comment] 2016-12-09 18:53
@efsysefsys This seems to happen to me once in a while as well, particularly on local Vagrant installations. I have no idea what causes it, but usually rebooting the VM/VPS in question resolves the issue.

**Comment by SlvrEagle23** [comment] 2016-12-14 19:17
Closing this issue for now, as issues like this seem to have been caused by an issue where PHP would overspawn "zombie" instances of liquidsoap and/or icecast2, causing the machine to run out of memory, thus triggering the "can't fork" errors.

The push to use supervisord for these things should have entirely resolved this issue. As part of the update script, all existing liquidsoap/icecast2/sc_trans processes are terminated as supervisord takes over.

**Closed by SlvrEagle23** 2016-12-14 19:17 UTC
